version: '3'
services:
    db:
        image: postgres:11.6
    webpacker:
        build:
            context: .
        volumes:
        - .:/production
        ports:
        - "80:3000"
        environment:
            PORT: "3000"
            PGHOST: "db"
            PGUSER: "postgres"
            PGDBNAME: "production"
        depends_on:
        - db